<a href="https://colab.research.google.com/github/Pritishcoder07/AIMLP/blob/main/Basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


#  Array Creation with Numpy


**Conversion from other Python structures (e.g., lists, tuples)**

In [ ]:
import numpy as np

In [ ]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listarray.shape


(3, 3)

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray[0,1]=10

In [ ]:
listarray

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
listarray.size

9

In [ ]:
Heloo = np.array([[1,2,8,7,6,50,56]])

In [ ]:
Heloo[0,1]=55

In [ ]:
Heloo


array([[ 1, 55,  8,  7,  6, 50, 56]])

**Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)**

In [ ]:
zeros = np.zeros([2,15])


In [ ]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
range =np.arange(20)

In [ ]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

** BASICS ML ATTRIBUTE **

In [ ]:
arr = ([1,2,3],[4,5,6],[7,8,9])
arr

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [ ]:
arr2 = np.array(arr)

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.sum(axis=0)

array([12, 15, 18])

In [ ]:
arr2.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
arr2.argmax()


np.int64(8)

In [ ]:
arr2.argmin()

np.int64(0)

In [ ]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
total =listarray+arr2

In [ ]:
total

array([[ 2, 12,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
total2 =total *2
total2

array([[ 4, 24, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [ ]:
np.sqrt(total2)

array([[2.        , 4.89897949, 3.46410162],
       [4.        , 4.47213595, 4.89897949],
       [5.29150262, 5.65685425, 6.        ]])