<a href="https://colab.research.google.com/github/Pritishcoder07/AIMLP/blob/main/Basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


#  Array Creation with Numpy


**Conversion from other Python structures (e.g., lists, tuples)**

In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
listarray.shape


(3, 3)

In [5]:
listarray.dtype

dtype('int64')

In [6]:
listarray[0,1]=10

In [7]:
listarray

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [8]:
listarray.size

9

In [9]:
Heloo = np.array([[1,2,8,7,6,50,56]])

In [10]:
Heloo[0,1]=55

In [11]:
Heloo


array([[ 1, 55,  8,  7,  6, 50, 56]])

**Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)**

In [12]:
zeros = np.zeros([2,15])


In [13]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
range =np.arange(20)

In [15]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

** BASICS ML ATTRIBUTE **

In [17]:
arr = ([1,2,3],[4,5,6],[7,8,9])
arr

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [18]:
arr2 = np.array(arr)

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2.sum(axis=0)

array([12, 15, 18])

In [21]:
arr2.sum(axis=1)

array([ 6, 15, 24])

In [22]:
arr2.argmax()


np.int64(8)

In [23]:
arr2.argmin()

np.int64(0)

In [24]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [25]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr2.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
total =listarray+arr2

In [29]:
total

array([[ 2, 12,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [30]:
total2 =total *2
total2

array([[ 4, 24, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [31]:
np.sqrt(total2)

array([[2.        , 4.89897949, 3.46410162],
       [4.        , 4.47213595, 4.89897949],
       [5.29150262, 5.65685425, 6.        ]])

# PANDAS


In [32]:
import pandas as pd


In [33]:
dict1 ={
    "name":['harry','rohan','skillf','shubh'],
    "marks":[92,34,24,30],
    "city":['rampur','kolkata','bareilly','antartica']
}

In [34]:
df = pd.DataFrame(dict1)
df



name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24   bareilly
3   shubh     30  antartica

In [35]:
df.to_csv('hello.csv')


In [36]:
df.to_csv('friends.csv',index=False)

In [37]:
df.head(1)


name  marks    city
0  harry     92  rampur

In [38]:
df.tail(2)

name  marks       city
2  skillf     24   bareilly
3   shubh     30  antartica

In [39]:
df.describe()

marks
count   4.000000
mean   45.000000
std    31.601688
min    24.000000
25%    28.500000
50%    32.000000
75%    48.500000
max    92.000000

In [40]:
newdf = pd.DataFrame(np.random.rand(10000))


In [41]:
type(newdf)

pandas.core.frame.DataFrame

In [42]:
newdf.dtypes

0    float64
dtype: object

In [43]:
newdf

0
0     0.320189
1     0.313515
2     0.334941
3     0.936936
4     0.400699
...        ...
9995  0.894752
9996  0.118426
9997  0.691125
9998  0.964525
9999  0.797353

[10000 rows x 1 columns]

# DATA CLEANING

In [44]:
import pandas as pd


In [45]:
from google.colab import files
upload  = files.upload()

Saving dirty_dataset_1000.csv to dirty_dataset_1000.csv


In [46]:
messdata = pd.read_csv('dirty_dataset_1000.csv')

In [47]:
messdata

Name     Age  Gender    City Salary        Date  \
0     Deborah Anderson     200    Male  Mumbai  82481  2021-04-16   
1                  NaN      16    Male  Bhopal    50k  2024-01-09   
2            James Liu  twenty  Female   Delhi  90438  2023-02-10   
3           Aaron Ford     200     NaN  Bhopal   -inf  2024-11-07   
4        Andrea Mercer       0     NaN  Nagpur  62322  2023-08-05   
...                ...     ...     ...     ...    ...         ...   
1015      Robert Gibbs      19  Female  Bhopal  32982  2021-08-29   
1016       Steven Peck     200    Male  Nagpur    inf  2021-07-16   
1017       Steve Munoz  twenty     NaN  Bhopal   -inf  32-13-2020   
1018         Zoe Black     NaN       F     NaN  69566  2023-11-29   
1019     Benjamin West     NaN    Male     NaN    NaN  2023-10-14   

                   Phone  Marks Passed  
0                    NaN   30.0    NaN  
1                    NaN  -20.0    Yes  
2     651-509-7684x87571  150.0   True  
3             0002108269  -20.0    Yes  
4             0006512234    NaN     No  
...                  ...    ...    ...  
1015          0005006861    NaN   True  
1016                 NaN    NaN    Yes  
1017                 NaN   45.0  False  
1018                 NaN    NaN  False  
1019                 NaN   92.0    NaN  

[1020 rows x 9 columns]

In [48]:
messdata.head(10)

Name     Age  Gender    City Salary        Date  \
0  Deborah Anderson     200    Male  Mumbai  82481  2021-04-16   
1               NaN      16    Male  Bhopal    50k  2024-01-09   
2         James Liu  twenty  Female   Delhi  90438  2023-02-10   
3        Aaron Ford     200     NaN  Bhopal   -inf  2024-11-07   
4     Andrea Mercer       0     NaN  Nagpur  62322  2023-08-05   
5      Anthony Cruz     200       F  Bhopal    inf  2024-12-16   
6      Hannah Dixon     NaN     NaN  Nagpur   -inf  2024-12-13   
7   Jennifer Hayden     NaN     NaN  Bhopal    NaN  2025-10-02   
8     Daniel Thomas  twenty    Male  Raipur    inf  2022-12-14   
9       Sean Guzman     NaN       M  Mumbai  98541  2023-12-27   

                Phone  Marks Passed  
0                 NaN   30.0    NaN  
1                 NaN  -20.0    Yes  
2  651-509-7684x87571  150.0   True  
3          0002108269  -20.0    Yes  
4          0006512234    NaN     No  
5          0001672450    1.0   True  
6   (834)239-1491x362  -20.0     No  
7                 NaN    NaN    Yes  
8       (708)542-0995  -20.0     No  
9                 NaN    NaN    NaN

In [49]:
messdata.isnull().sum()*100/len(messdata)

Name       5.588235
Age       24.607843
Gender    31.666667
City      24.803922
Salary    19.215686
Date       0.000000
Phone     52.647059
Marks     26.176471
Passed    35.980392
dtype: float64

In [50]:
messdata['Name'].unique()

array(['Deborah Anderson', nan, 'James Liu', 'Aaron Ford',
       'Andrea Mercer', 'Anthony Cruz', 'Hannah Dixon', 'Jennifer Hayden',
       'Daniel Thomas', 'Sean Guzman', 'Raymond Lara', 'John Brown',
       'Mr. Dennis Benjamin', 'Susan Chandler', 'Kimberly King',
       'Robert Gibbs', 'Steven Peck', 'Steve Munoz', 'Zoe Black',
       'Benjamin West', 'Jeffrey Munoz', 'Ariel Perez', 'Zachary Garcia',
       'Kimberly Terrell', 'Gary Chapman', 'Tiffany Webster',
       'Mrs. Misty Bryan', 'Chelsey Neal', 'Ashley White', 'Jane Evans',
       'Travis Scott', 'Samantha Miller', 'Linda Marshall DVM',
       'Ivan Adams', 'Alison Hill', 'Gerald Molina', 'Laura Glover',
       'James Johns', 'Todd Harris', 'David Cohen', 'Joseph Thomas',
       'Stephen Peck', 'Denise Baker', 'Andrew Roberts', 'Angela Gibson',
       'Alyssa Lawrence', 'Sarah Pearson', 'Brandy Clark',
       'Daisy Jackson', 'Jason Hunter', 'Andre Dixon', 'Amanda Baker',
       'Ruben Wilson', 'Candice Meyers', 'Elizabeth

In [53]:
messdata

Name     Age  Gender    City Salary        Date  \
0     Deborah Anderson     200    Male  Mumbai  82481  2021-04-16   
1                  NaN      16    Male  Bhopal    50k  2024-01-09   
2            James Liu  twenty  Female   Delhi  90438  2023-02-10   
3           Aaron Ford     200     NaN  Bhopal   -inf  2024-11-07   
4        Andrea Mercer       0     NaN  Nagpur  62322  2023-08-05   
...                ...     ...     ...     ...    ...         ...   
1015      Robert Gibbs      19  Female  Bhopal  32982  2021-08-29   
1016       Steven Peck     200    Male  Nagpur    inf  2021-07-16   
1017       Steve Munoz  twenty     NaN  Bhopal   -inf  32-13-2020   
1018         Zoe Black     NaN       F     NaN  69566  2023-11-29   
1019     Benjamin West     NaN    Male     NaN    NaN  2023-10-14   

                   Phone  Marks Passed  
0                    NaN   30.0    NaN  
1                    NaN  -20.0    Yes  
2     651-509-7684x87571  150.0   True  
3             0002108269  -20.0    Yes  
4             0006512234    NaN     No  
...                  ...    ...    ...  
1015          0005006861    NaN   True  
1016                 NaN    NaN    Yes  
1017                 NaN   45.0  False  
1018                 NaN    NaN  False  
1019                 NaN   92.0    NaN  

[1020 rows x 9 columns]

In [54]:
messdata.dtypes


Name       object
Age        object
Gender     object
City       object
Salary     object
Date       object
Phone      object
Marks     float64
Passed     object
dtype: object

In [55]:
messdata['Age'].fillna(0,inplace=True)

/tmp/ipython-input-3655770196.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  messdata['Age'].fillna(0,inplace=True)


In [58]:
print("hello world")

hello world
