<a href="https://colab.research.google.com/github/Pritishcoder07/AIMLP/blob/main/Basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY


#  Array Creation with Numpy


**Conversion from other Python structures (e.g., lists, tuples)**

In [ ]:
import numpy as np

In [ ]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listarray.shape


(3, 3)

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray[0,1]=10

In [ ]:
listarray

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
listarray.size

9

In [ ]:
Heloo = np.array([[1,2,8,7,6,50,56]])

In [ ]:
Heloo[0,1]=55

In [ ]:
Heloo


array([[ 1, 55,  8,  7,  6, 50, 56]])

**Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)**

In [ ]:
zeros = np.zeros([2,15])


In [ ]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
range =np.arange(20)

In [ ]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

** BASICS ML ATTRIBUTE **

In [ ]:
arr = ([1,2,3],[4,5,6],[7,8,9])
arr

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [ ]:
arr2 = np.array(arr)

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.sum(axis=0)

array([12, 15, 18])

In [ ]:
arr2.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
arr2.argmax()


np.int64(8)

In [ ]:
arr2.argmin()

np.int64(0)

In [ ]:
arr2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
total =listarray+arr2

In [ ]:
total

array([[ 2, 12,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
total2 =total *2
total2

array([[ 4, 24, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [ ]:
np.sqrt(total2)

array([[2.        , 4.89897949, 3.46410162],
       [4.        , 4.47213595, 4.89897949],
       [5.29150262, 5.65685425, 6.        ]])

# PANDAS


In [ ]:
import pandas as pd


In [ ]:
dict1 ={
    "name":['harry','rohan','skillf','shubh'],
    "marks":[92,34,24,30],
    "city":['rampur','kolkata','bareilly','antartica']
}

In [ ]:
df = pd.DataFrame(dict1)
df



name  marks       city
0   harry     92     rampur
1   rohan     34    kolkata
2  skillf     24   bareilly
3   shubh     30  antartica

In [ ]:
df.to_csv('hello.csv')


In [ ]:
df.to_csv('friends.csv',index=False)

In [ ]:
df.head(1)


name  marks    city
0  harry     92  rampur

In [ ]:
df.tail(2)

name  marks       city
2  skillf     24   bareilly
3   shubh     30  antartica

In [ ]:
df.describe()

marks
count   4.000000
mean   45.000000
std    31.601688
min    24.000000
25%    28.500000
50%    32.000000
75%    48.500000
max    92.000000

In [ ]:
newdf = pd.DataFrame(np.random.rand(10000))


In [ ]:
type(newdf)

pandas.core.frame.DataFrame

In [ ]:
newdf.dtypes

0    float64
dtype: object

In [ ]:
newdf

0
0     0.186195
1     0.735613
2     0.748443
3     0.526691
4     0.765734
...        ...
9995  0.596057
9996  0.488248
9997  0.621681
9998  0.657671
9999  0.849110

[10000 rows x 1 columns]

# DATA CLEANING

In [ ]:
import pandas as pd


In [ ]:
from google.colab import files
upload  = files.upload()

Saving netflix1.csv.zip to netflix1.csv (1).zip


In [ ]:
messdata = pd.read_csv('netflix1.csv.zip')

In [ ]:
messdata



show_id     type                             title         director  \
0         s1    Movie              Dick Johnson Is Dead  Kirsten Johnson   
1         s3  TV Show                         Ganglands  Julien Leclercq   
2         s6  TV Show                     Midnight Mass    Mike Flanagan   
3        s14    Movie  Confessions of an Invisible Girl    Bruno Garotti   
4         s8    Movie                           Sankofa     Haile Gerima   
...      ...      ...                               ...              ...   
8785   s8797  TV Show                        Yunus Emre        Not Given   
8786   s8798  TV Show                         Zak Storm        Not Given   
8787   s8801  TV Show                Zindagi Gulzar Hai        Not Given   
8788   s8784  TV Show                              Yoko        Not Given   
8789   s8786  TV Show                               YOM        Not Given   

            country  date_added  release_year rating   duration  \
0     United States   9/25/2021          2020  PG-13     90 min   
1            France   9/24/2021          2021  TV-MA   1 Season   
2     United States   9/24/2021          2021  TV-MA   1 Season   
3            Brazil   9/22/2021          2021  TV-PG     91 min   
4     United States   9/24/2021          1993  TV-MA    125 min   
...             ...         ...           ...    ...        ...   
8785         Turkey   1/17/2017          2016  TV-PG  2 Seasons   
8786  United States   9/13/2018          2016  TV-Y7  3 Seasons   
8787       Pakistan  12/15/2016          2012  TV-PG   1 Season   
8788       Pakistan   6/23/2018          2016   TV-Y   1 Season   
8789       Pakistan    6/7/2018          2016  TV-Y7   1 Season   

                                              listed_in  
0                                         Documentaries  
1     Crime TV Shows, International TV Shows, TV Act...  
2                    TV Dramas, TV Horror, TV Mysteries  
3                    Children & Family Movies, Comedies  
4      Dramas, Independent Movies, International Movies  
...                                                 ...  
8785                  International TV Shows, TV Dramas  
8786                                           Kids' TV  
8787  International TV Shows, Romantic TV Shows, TV ...  
8788                                           Kids' TV  
8789                                           Kids' TV  

[8790 rows x 10 columns]

In [ ]:
messdata.head(5)

show_id     type                             title         director  \
0      s1    Movie              Dick Johnson Is Dead  Kirsten Johnson   
1      s3  TV Show                         Ganglands  Julien Leclercq   
2      s6  TV Show                     Midnight Mass    Mike Flanagan   
3     s14    Movie  Confessions of an Invisible Girl    Bruno Garotti   
4      s8    Movie                           Sankofa     Haile Gerima   

         country date_added  release_year rating  duration  \
0  United States  9/25/2021          2020  PG-13    90 min   
1         France  9/24/2021          2021  TV-MA  1 Season   
2  United States  9/24/2021          2021  TV-MA  1 Season   
3         Brazil  9/22/2021          2021  TV-PG    91 min   
4  United States  9/24/2021          1993  TV-MA   125 min   

                                           listed_in  
0                                      Documentaries  
1  Crime TV Shows, International TV Shows, TV Act...  
2                 TV Dramas, TV Horror, TV Mysteries  
3                 Children & Family Movies, Comedies  
4   Dramas, Independent Movies, International Movies

In [ ]:
messdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64 
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB


In [ ]:
messdata.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [ ]:
messdata['show_id']

0          s1
1          s3
2          s6
3         s14
4          s8
        ...  
8785    s8797
8786    s8798
8787    s8801
8788    s8784
8789    s8786
Name: show_id, Length: 8790, dtype: object